= 6.0 Migration Guide
:toc:

This guide discusses migration from Hibernate ORM version 5.2 to version 6.0.  For migration from
earlier versions, see any other pertinent migration guides as well.

== Background

6.0 introduces major changes, such as:

* refactoring Hibernate's Type contract to unify Hibernate ORM, JPA and SQM type systems
* migration to SQM for query interpretation/representation
** HQL/JPQL
** (JPA) criteria queries

Additionally, `hibernate-envers` has been made part of `hibernate-core` and better integrated
from an API perspective.


== Things that (might) make sense in a boot-only ServiceRegistry

* ClassmateContext
* Jandex/HCANN access
* BasicTypeProducerRegistry


== Misc

* removed `org.hibernate.type.TypeHelper` and `org.hibernate.type.TypeResolver`, as well as methods exposing
	access to them.  For the most part, replace with calls to `org.hibernate.Metamodel`
	and/or `org.hibernate.type.spi.TypeConfiguration`.
* removed `org.hibernate.type.TypeFactory` in favor of `TypeConfiguration`
*  I think SqlTypeDescriptor should have some say in determining the JdbcLiteralFormatter to use.  Currently this is
	defined on the mapper Type and the JavaTypeDescriptor.  But really its the fact that its a VARCHAR that dictates
	that a literal should be quoted, e.g.
* Moved `org.hibernate.jpa.event.spi.jpa.ExtendedBeanManager` to `org.hibernate.resource.cdi.spi.ExtendedBeanManager`
