/*
 * Hibernate, Relational Persistence for Idiomatic Java
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later.
 * See the lgpl.txt file in the root directory or http://www.gnu.org/licenses/lgpl-2.1.html.
 */
package org.hibernate.boot.jandex.spi;

import java.util.function.Consumer;

import org.hibernate.annotations.*;

import static org.hibernate.boot.jandex.spi.AnnotationDetails.createDetails;

/**
 * Details about Hibernate annotations
 *
 * @author Steve Ebersole
 */
public interface HibernateAnnotations {
	// todo (jandex) : inner/nested annotations?

	AnnotationDetails ANY = createDetails( Any.class );
	AnnotationDetails ANY_DISCRIMINATOR = createDetails( AnyDiscriminator.class );
	AnnotationDetails ANY_DISCRIMINATOR_VALUES = createDetails( AnyDiscriminatorValues.class );
	AnnotationDetails ANY_DISCRIMINATOR_VALUE = createDetails( AnyDiscriminatorValue.class, ANY_DISCRIMINATOR_VALUES );
	AnnotationDetails ANY_KEY_JAVA_CLASS = createDetails( AnyKeyJavaClass.class );
	AnnotationDetails ANY_KEY_JAVA_TYPE = createDetails( AnyKeyJavaType.class );
	AnnotationDetails ANY_KEY_JDBC_TYPE = createDetails( AnyKeyJdbcType.class );
	AnnotationDetails ANY_KEY_JDBC_TYPE_CODE = createDetails( AnyKeyJdbcTypeCode.class );
	AnnotationDetails ATTRIBUTE_ACCESSOR = createDetails( AttributeAccessor.class );
	AnnotationDetails ATTRIBUTE_BINDER_TYPE = createDetails( AttributeBinderType.class );
	AnnotationDetails BAG = createDetails( Bag.class );
	AnnotationDetails BATCH_SIZE = createDetails( BatchSize.class );
	AnnotationDetails CACHE = createDetails( Cache.class );
	AnnotationDetails CASCADE = createDetails( Cascade.class );
	AnnotationDetails CHECKS = createDetails( Checks.class );
	AnnotationDetails CHECK = createDetails( Check.class, CHECKS );
	AnnotationDetails COLLECTION_ID = createDetails( CollectionId.class );
	AnnotationDetails COLLECTION_ID_JAVA_TYPE = createDetails( CollectionIdJavaType.class );
	AnnotationDetails COLLECTION_ID_JDBC_TYPE = createDetails( CollectionIdJdbcType.class );
	AnnotationDetails COLLECTION_ID_JDBC_TYPE_CODE = createDetails( CollectionIdJdbcTypeCode.class );
	AnnotationDetails COLLECTION_ID_MUTABILITY = createDetails( CollectionIdMutability.class );
	AnnotationDetails COLLECTION_ID_TYPE = createDetails( CollectionIdType.class );
	AnnotationDetails COLLECTION_TYPE = createDetails( CollectionType.class );
	AnnotationDetails COLLECTION_TYPE_REGS = createDetails( CollectionTypeRegistrations.class );
	AnnotationDetails COLLECTION_TYPE_REG = createDetails( CollectionTypeRegistration.class, COLLECTION_TYPE_REGS );
	AnnotationDetails COLUMN_DEFAULT = createDetails( ColumnDefault.class );
	AnnotationDetails COLUMN_TRANSFORMERS = createDetails( ColumnTransformers.class );
	AnnotationDetails COLUMN_TRANSFORMER = createDetails( ColumnTransformer.class, COLUMN_TRANSFORMERS );
	AnnotationDetails COMMENT = createDetails( Comment.class );
	AnnotationDetails COMPOSITE_TYPE = createDetails( CompositeType.class );
	AnnotationDetails COMPOSITE_TYPE_REGS = createDetails( CompositeTypeRegistrations.class );
	AnnotationDetails COMPOSITE_TYPE_REG = createDetails( CompositeTypeRegistration.class, COMPOSITE_TYPE_REGS );
	AnnotationDetails CONVERTER_REGS = createDetails( ConverterRegistrations.class );
	AnnotationDetails CONVERTER_REG = createDetails( ConverterRegistration.class, CONVERTER_REGS );
	AnnotationDetails CREATION_TIMESTAMP = createDetails( CreationTimestamp.class );
	AnnotationDetails CURRENT_TIMESTAMP = createDetails( CurrentTimestamp.class );
	AnnotationDetails DISCRIMINATOR_FORMULA = createDetails( DiscriminatorFormula.class );
	AnnotationDetails DISCRIMINATOR_OPTIONS = createDetails( DiscriminatorOptions.class );
	AnnotationDetails DYNAMIC_INSERT = createDetails( DynamicInsert.class );
	AnnotationDetails DYNAMIC_UPDATE = createDetails( DynamicUpdate.class );
	AnnotationDetails EMBEDDABLE_INSTANTIATOR = createDetails( EmbeddableInstantiator.class );
	AnnotationDetails EMBEDDABLE_INSTANTIATOR_REGS = createDetails( EmbeddableInstantiatorRegistrations.class );
	AnnotationDetails EMBEDDABLE_INSTANTIATOR_REG = createDetails( EmbeddableInstantiatorRegistration.class, EMBEDDABLE_INSTANTIATOR_REGS );
	AnnotationDetails FETCH = createDetails( Fetch.class );
	AnnotationDetails FETCH_PROFILES = createDetails( FetchProfiles.class );
	AnnotationDetails FETCH_PROFILE = createDetails( FetchProfile.class, FETCH_PROFILES );
	AnnotationDetails FILTERS = createDetails( Filters.class );
	AnnotationDetails FILTER = createDetails( Filter.class, FILTERS );
	AnnotationDetails FILTER_DEFS = createDetails( FilterDefs.class );
	AnnotationDetails FILTER_DEF = createDetails( FilterDef.class, FILTER_DEFS );
	AnnotationDetails FILTER_JOIN_TABLES = createDetails( FilterJoinTables.class );
	AnnotationDetails FILTER_JOIN_TABLE = createDetails( FilterJoinTable.class, FILTER_JOIN_TABLES );
	AnnotationDetails FOREIGN_KEY = createDetails( ForeignKey.class );
	AnnotationDetails FORMULA = createDetails( Formula.class );
	AnnotationDetails GENERATED = createDetails( Generated.class );
	AnnotationDetails GENERATED_COLUMN = createDetails( GeneratedColumn.class );
	AnnotationDetails GENERATOR_TYPE = createDetails( GeneratorType.class );
	AnnotationDetails GENERIC_GENERATORS = createDetails( GenericGenerators.class );
	AnnotationDetails GENERIC_GENERATOR = createDetails( GenericGenerator.class, GENERIC_GENERATORS );
	AnnotationDetails ID_GENERATOR_TYPE = createDetails( IdGeneratorType.class );
	AnnotationDetails IMMUTABLE = createDetails( Immutable.class );
	AnnotationDetails IMPORTED = createDetails( Imported.class );
	AnnotationDetails INDEX = createDetails( Index.class );
	AnnotationDetails INDEX_COLUMN = createDetails( IndexColumn.class );
	AnnotationDetails INSTANTIATOR = createDetails( Instantiator.class );
	AnnotationDetails JAVA_TYPE = createDetails( JavaType.class );
	AnnotationDetails JAVA_TYPE_REGS = createDetails( JavaTypeRegistrations.class );
	AnnotationDetails JAVA_TYPE_REG = createDetails( JavaTypeRegistration.class, JAVA_TYPE_REGS );
	AnnotationDetails JDBC_TYPE = createDetails( JdbcType.class );
	AnnotationDetails JDBC_TYPE_CODE = createDetails( JdbcTypeCode.class );
	AnnotationDetails JDBC_TYPE_REGS = createDetails( JdbcTypeRegistrations.class );
	AnnotationDetails JDBC_TYPE_REG = createDetails( JdbcTypeRegistration.class, JDBC_TYPE_REGS );
	AnnotationDetails JOIN_COLUMNS_OR_FORMULAS = createDetails( JoinColumnsOrFormulas.class );
	AnnotationDetails JOIN_COLUMN_OR_FORMULA = createDetails( JoinColumnOrFormula.class, JOIN_COLUMNS_OR_FORMULAS );
	AnnotationDetails JOIN_FORMULA = createDetails( JoinFormula.class );
	AnnotationDetails LAZY_COLLECTION = createDetails( LazyCollection.class );
	AnnotationDetails LAZY_GROUP = createDetails( LazyGroup.class );
	AnnotationDetails LAZY_TO_ONE = createDetails( LazyToOne.class );
	AnnotationDetails LIST_INDEX_BASE = createDetails( ListIndexBase.class );
	AnnotationDetails LIST_INDEX_JAVA_TYPE = createDetails( ListIndexJavaType.class );
	AnnotationDetails LIST_INDEX_JDBC_TYPE = createDetails( ListIndexJdbcType.class );
	AnnotationDetails LIST_INDEX_JDBC_TYPE_CODE = createDetails( ListIndexJdbcTypeCode.class );
	AnnotationDetails LOADER = createDetails( Loader.class );
	AnnotationDetails MANY_TO_ANY = createDetails( ManyToAny.class );
	AnnotationDetails MAP_KEY_COMPOSITE_TYPE = createDetails( MapKeyCompositeType.class );
	AnnotationDetails MAP_KEY_JAVA_TYPE = createDetails( MapKeyJavaType.class );
	AnnotationDetails MAP_KEY_JDBC_TYPE = createDetails( MapKeyJdbcType.class );
	AnnotationDetails MAP_KEY_JDBC_TYPE_CODE = createDetails( MapKeyJdbcTypeCode.class );
	AnnotationDetails MAP_KEY_MUTABILITY = createDetails( MapKeyMutability.class );
	AnnotationDetails MAP_KEY_TYPE = createDetails( MapKeyType.class );
	AnnotationDetails MUTABILITY = createDetails( Mutability.class );
	AnnotationDetails NAMED_NATIVE_QUERIES = createDetails( NamedNativeQueries.class );
	AnnotationDetails NAMED_NATIVE_QUERY = createDetails( NamedNativeQuery.class, NAMED_NATIVE_QUERIES );
	AnnotationDetails NAMED_QUERIES = createDetails( NamedQueries.class );
	AnnotationDetails NAMED_QUERY = createDetails( NamedQuery.class, NAMED_QUERIES );
	AnnotationDetails NATIONALIZED = createDetails( Nationalized.class );
	AnnotationDetails NATURAL_ID = createDetails( NaturalId.class );
	AnnotationDetails NATURAL_ID_CACHE = createDetails( NaturalIdCache.class );
	AnnotationDetails NOT_FOUND = createDetails( NotFound.class );
	AnnotationDetails ON_DELETE = createDetails( OnDelete.class );
	AnnotationDetails OPTIMISTIC_LOCK = createDetails( OptimisticLock.class );
	AnnotationDetails OPTIMISTIC_LOCKING = createDetails( OptimisticLocking.class );
	AnnotationDetails ORDER_BY = createDetails( OrderBy.class );
	AnnotationDetails PARAM_DEF = createDetails( ParamDef.class );
	AnnotationDetails PARAMETER = createDetails( Parameter.class );
	AnnotationDetails PARENT = createDetails( Parent.class );
	AnnotationDetails PARTITION_KEY = createDetails( PartitionKey.class );
	AnnotationDetails PERSISTER = createDetails( Persister.class );
	AnnotationDetails POLYMORPHISM = createDetails( Polymorphism.class );
	AnnotationDetails PROXY = createDetails( Proxy.class );
	AnnotationDetails ROW_ID = createDetails( RowId.class );
	AnnotationDetails SECONDARY_ROWS = createDetails( SecondaryRows.class );
	AnnotationDetails SECONDARY_ROW = createDetails( SecondaryRow.class, SECONDARY_ROWS );
	AnnotationDetails SELECT_BEFORE_UPDATE = createDetails( SelectBeforeUpdate.class );
	AnnotationDetails SORT_COMPARATOR = createDetails( SortComparator.class );
	AnnotationDetails SORT_NATURAL = createDetails( SortNatural.class );
	AnnotationDetails SOURCE = createDetails( Source.class );
	AnnotationDetails SQL_DELETES = createDetails( SQLDeletes.class );
	AnnotationDetails SQL_DELETE = createDetails( SQLDelete.class, SQL_DELETES );
	AnnotationDetails SQL_DELETE_ALL = createDetails( SQLDeleteAll.class );
	AnnotationDetails SQL_FRAGMENT_ALIAS = createDetails( SqlFragmentAlias.class );
	AnnotationDetails SQL_INSERTS = createDetails( SQLInserts.class );
	AnnotationDetails SQL_INSERT = createDetails( SQLInsert.class, SQL_INSERTS );
	AnnotationDetails SQL_UPDATES = createDetails( SQLUpdates.class );
	AnnotationDetails SQL_UPDATE = createDetails( SQLUpdate.class, SQL_UPDATES );
	AnnotationDetails STRUCT = createDetails( Struct.class );
	AnnotationDetails SUBSELECT = createDetails( Subselect.class );
	AnnotationDetails SYNCHRONIZE = createDetails( Synchronize.class );
	AnnotationDetails TABLES = createDetails( Tables.class );
	AnnotationDetails TABLE = createDetails( Table.class, TABLES );
	AnnotationDetails TARGET = createDetails( Target.class );
	AnnotationDetails TENANT_ID = createDetails( TenantId.class );
	AnnotationDetails TZ_COLUMN = createDetails( TimeZoneColumn.class );
	AnnotationDetails TZ_STORAGE = createDetails( TimeZoneStorage.class );
	AnnotationDetails TYPE = createDetails( Type.class );
	AnnotationDetails TYPE_BINDER_TYPE = createDetails( TypeBinderType.class );
	AnnotationDetails TYPE_REGS = createDetails( TypeRegistrations.class );
	AnnotationDetails TYPE_REG = createDetails( TypeRegistration.class, TYPE_REGS );
	AnnotationDetails UPDATE_TIMESTAMP = createDetails( UpdateTimestamp.class );
	AnnotationDetails UUID_GENERATOR = createDetails( UuidGenerator.class );
	AnnotationDetails VALUE_GENERATION_TYPE = createDetails( ValueGenerationType.class );
	AnnotationDetails WHERE = createDetails( Where.class );
	AnnotationDetails WHERE_JOIN_TABLE = createDetails( WhereJoinTable.class );


	AnnotationDetails DIALECT_OVERRIDE_CHECKS = createDetails( DialectOverride.Checks.class );
	AnnotationDetails DIALECT_OVERRIDE_CHECK = createDetails( DialectOverride.Check.class, DIALECT_OVERRIDE_CHECKS );
	AnnotationDetails DIALECT_OVERRIDE_ORDER_BYS = createDetails( DialectOverride.OrderBys.class );
	AnnotationDetails DIALECT_OVERRIDE_ORDER_BY = createDetails( DialectOverride.OrderBy.class, DIALECT_OVERRIDE_ORDER_BYS );
	AnnotationDetails DIALECT_OVERRIDE_COLUMN_DEFAULTS = createDetails( DialectOverride.ColumnDefaults.class );
	AnnotationDetails DIALECT_OVERRIDE_COLUMN_DEFAULT = createDetails( DialectOverride.ColumnDefault.class, DIALECT_OVERRIDE_COLUMN_DEFAULTS );
	AnnotationDetails DIALECT_OVERRIDE_GENERATED_COLUMNS = createDetails( DialectOverride.GeneratedColumns.class );
	AnnotationDetails DIALECT_OVERRIDE_GENERATED_COLUMN = createDetails( DialectOverride.GeneratedColumn.class, DIALECT_OVERRIDE_GENERATED_COLUMNS );
	AnnotationDetails DIALECT_OVERRIDE_DISCRIMINATOR_FORMULAS = createDetails( DialectOverride.DiscriminatorFormulas.class );
	AnnotationDetails DIALECT_OVERRIDE_DISCRIMINATOR_FORMULA = createDetails( DialectOverride.DiscriminatorFormula.class, DIALECT_OVERRIDE_DISCRIMINATOR_FORMULAS );
	AnnotationDetails DIALECT_OVERRIDE_FORMULAS = createDetails( DialectOverride.Formulas.class );
	AnnotationDetails DIALECT_OVERRIDE_FORMULA = createDetails( DialectOverride.Formula.class, DIALECT_OVERRIDE_FORMULAS );
	AnnotationDetails DIALECT_OVERRIDE_JOIN_FORMULAS = createDetails( DialectOverride.JoinFormulas.class );
	AnnotationDetails DIALECT_OVERRIDE_JOIN_FORMULA = createDetails( DialectOverride.JoinFormula.class, DIALECT_OVERRIDE_JOIN_FORMULAS );
	AnnotationDetails DIALECT_OVERRIDE_WHERES = createDetails( DialectOverride.Wheres.class );
	AnnotationDetails DIALECT_OVERRIDE_WHERE = createDetails( DialectOverride.Where.class, DIALECT_OVERRIDE_WHERES );
	AnnotationDetails DIALECT_OVERRIDE_FILTER_OVERRIDES = createDetails( DialectOverride.FilterOverrides.class );
	AnnotationDetails DIALECT_OVERRIDE_FILTERS = createDetails( DialectOverride.Filters.class, DIALECT_OVERRIDE_FILTER_OVERRIDES );
	AnnotationDetails DIALECT_OVERRIDE_FILTER_DEF_OVERRIDES = createDetails( DialectOverride.FilterDefOverrides.class );
	AnnotationDetails DIALECT_OVERRIDE_FILTER_DEFS = createDetails( DialectOverride.FilterDefs.class, DIALECT_OVERRIDE_FILTER_DEF_OVERRIDES );
	AnnotationDetails DIALECT_OVERRIDE_VERSION = createDetails( DialectOverride.Version.class );

	/**
	 * Consume each defined AnnotationDetails
	 */
	static void forEachAnnotation(Consumer<AnnotationDetails> consumer) {
		consumer.accept( ANY );
		consumer.accept( ANY_DISCRIMINATOR );
		consumer.accept( ANY_DISCRIMINATOR_VALUES );
		consumer.accept( ANY_DISCRIMINATOR_VALUE );
		consumer.accept( ANY_KEY_JAVA_CLASS );
		consumer.accept( ANY_KEY_JAVA_TYPE );
		consumer.accept( ANY_KEY_JDBC_TYPE );
		consumer.accept( ANY_KEY_JDBC_TYPE_CODE );
		consumer.accept( ATTRIBUTE_ACCESSOR );
		consumer.accept( ATTRIBUTE_BINDER_TYPE );
		consumer.accept( BAG );
		consumer.accept( BATCH_SIZE );
		consumer.accept( CACHE );
		consumer.accept( CASCADE );
		consumer.accept( CHECKS );
		consumer.accept( CHECK );
		consumer.accept( COLLECTION_ID );
		consumer.accept( COLLECTION_ID_JAVA_TYPE );
		consumer.accept( COLLECTION_ID_JDBC_TYPE );
		consumer.accept( COLLECTION_ID_JDBC_TYPE_CODE );
		consumer.accept( COLLECTION_ID_MUTABILITY );
		consumer.accept( COLLECTION_ID_TYPE );
		consumer.accept( COLLECTION_TYPE );
		consumer.accept( COLLECTION_TYPE_REGS );
		consumer.accept( COLLECTION_TYPE_REG );
		consumer.accept( COLUMN_DEFAULT );
		consumer.accept( COLUMN_TRANSFORMERS );
		consumer.accept( COLUMN_TRANSFORMER );
		consumer.accept( COMMENT );
		consumer.accept( COMPOSITE_TYPE );
		consumer.accept( COMPOSITE_TYPE_REGS );
		consumer.accept( COMPOSITE_TYPE_REG );
		consumer.accept( CONVERTER_REGS );
		consumer.accept( CONVERTER_REG );
		consumer.accept( CREATION_TIMESTAMP );
		consumer.accept( CURRENT_TIMESTAMP );
		consumer.accept( DISCRIMINATOR_FORMULA );
		consumer.accept( DISCRIMINATOR_OPTIONS );
		consumer.accept( DYNAMIC_INSERT );
		consumer.accept( DYNAMIC_UPDATE );
		consumer.accept( EMBEDDABLE_INSTANTIATOR );
		consumer.accept( EMBEDDABLE_INSTANTIATOR_REGS );
		consumer.accept( EMBEDDABLE_INSTANTIATOR_REG );
		consumer.accept( FETCH );
		consumer.accept( FETCH_PROFILES );
		consumer.accept( FETCH_PROFILE );
		consumer.accept( FILTER );
		consumer.accept( FILTERS );
		consumer.accept( FILTER_DEFS );
		consumer.accept( FILTER_DEF );
		consumer.accept( FILTER_JOIN_TABLES );
		consumer.accept( FILTER_JOIN_TABLE );
		consumer.accept( FOREIGN_KEY );
		consumer.accept( FORMULA );
		consumer.accept( GENERATED );
		consumer.accept( GENERATED_COLUMN );
		consumer.accept( GENERATOR_TYPE );
		consumer.accept( GENERIC_GENERATORS );
		consumer.accept( GENERIC_GENERATOR );
		consumer.accept( ID_GENERATOR_TYPE );
		consumer.accept( IMMUTABLE );
		consumer.accept( IMPORTED );
		consumer.accept( INDEX );
		consumer.accept( INDEX_COLUMN );
		consumer.accept( INSTANTIATOR );
		consumer.accept( JAVA_TYPE );
		consumer.accept( JAVA_TYPE_REGS );
		consumer.accept( JAVA_TYPE_REG );
		consumer.accept( JDBC_TYPE );
		consumer.accept( JDBC_TYPE_CODE );
		consumer.accept( JDBC_TYPE_REGS );
		consumer.accept( JDBC_TYPE_REG );
		consumer.accept( JOIN_COLUMNS_OR_FORMULAS );
		consumer.accept( JOIN_COLUMN_OR_FORMULA );
		consumer.accept( JOIN_FORMULA );
		consumer.accept( LAZY_COLLECTION );
		consumer.accept( LAZY_GROUP );
		consumer.accept( LAZY_TO_ONE );
		consumer.accept( LIST_INDEX_BASE );
		consumer.accept( LIST_INDEX_JAVA_TYPE );
		consumer.accept( LIST_INDEX_JDBC_TYPE );
		consumer.accept( LIST_INDEX_JDBC_TYPE_CODE );
		consumer.accept( LOADER );
		consumer.accept( MANY_TO_ANY );
		consumer.accept( MAP_KEY_COMPOSITE_TYPE );
		consumer.accept( MAP_KEY_JAVA_TYPE );
		consumer.accept( MAP_KEY_JDBC_TYPE );
		consumer.accept( MAP_KEY_JDBC_TYPE_CODE );
		consumer.accept( MAP_KEY_MUTABILITY );
		consumer.accept( MAP_KEY_TYPE );
		consumer.accept( MUTABILITY );
		consumer.accept( NAMED_NATIVE_QUERIES );
		consumer.accept( NAMED_NATIVE_QUERY );
		consumer.accept( NAMED_QUERIES );
		consumer.accept( NAMED_QUERY );
		consumer.accept( NATIONALIZED );
		consumer.accept( NATURAL_ID );
		consumer.accept( NATURAL_ID_CACHE );
		consumer.accept( NOT_FOUND );
		consumer.accept( ON_DELETE );
		consumer.accept( OPTIMISTIC_LOCK );
		consumer.accept( OPTIMISTIC_LOCKING );
		consumer.accept( ORDER_BY );
		consumer.accept( PARAM_DEF );
		consumer.accept( PARAMETER );
		consumer.accept( PARENT );
		consumer.accept( PARTITION_KEY );
		consumer.accept( PERSISTER );
		consumer.accept( POLYMORPHISM );
		consumer.accept( PROXY );
		consumer.accept( ROW_ID );
		consumer.accept( SECONDARY_ROWS );
		consumer.accept( SECONDARY_ROW );
		consumer.accept( SELECT_BEFORE_UPDATE );
		consumer.accept( SORT_COMPARATOR );
		consumer.accept( SORT_NATURAL );
		consumer.accept( SOURCE );
		consumer.accept( SQL_DELETE_ALL );
		consumer.accept( SQL_DELETES );
		consumer.accept( SQL_DELETE );
		consumer.accept( SQL_FRAGMENT_ALIAS );
		consumer.accept( SQL_INSERTS );
		consumer.accept( SQL_INSERT );
		consumer.accept( SQL_UPDATES );
		consumer.accept( SQL_UPDATE );
		consumer.accept( STRUCT );
		consumer.accept( SUBSELECT );
		consumer.accept( SYNCHRONIZE );
		consumer.accept( TABLES );
		consumer.accept( TABLE );
		consumer.accept( TARGET );
		consumer.accept( TENANT_ID );
		consumer.accept( TZ_COLUMN );
		consumer.accept( TZ_STORAGE );
		consumer.accept( TYPE );
		consumer.accept( TYPE_BINDER_TYPE );
		consumer.accept( TYPE_REGS );
		consumer.accept( TYPE_REG );
		consumer.accept( UPDATE_TIMESTAMP );
		consumer.accept( UUID_GENERATOR );
		consumer.accept( VALUE_GENERATION_TYPE );
		consumer.accept( WHERE );
		consumer.accept( WHERE_JOIN_TABLE );

		consumer.accept( DIALECT_OVERRIDE_CHECKS );
		consumer.accept( DIALECT_OVERRIDE_CHECK );
		consumer.accept( DIALECT_OVERRIDE_ORDER_BYS );
		consumer.accept( DIALECT_OVERRIDE_ORDER_BY );
		consumer.accept( DIALECT_OVERRIDE_COLUMN_DEFAULTS );
		consumer.accept( DIALECT_OVERRIDE_COLUMN_DEFAULT );
		consumer.accept( DIALECT_OVERRIDE_GENERATED_COLUMNS );
		consumer.accept( DIALECT_OVERRIDE_GENERATED_COLUMN );
		consumer.accept( DIALECT_OVERRIDE_DISCRIMINATOR_FORMULAS );
		consumer.accept( DIALECT_OVERRIDE_DISCRIMINATOR_FORMULA );
		consumer.accept( DIALECT_OVERRIDE_FORMULAS );
		consumer.accept( DIALECT_OVERRIDE_FORMULA );
		consumer.accept( DIALECT_OVERRIDE_JOIN_FORMULAS );
		consumer.accept( DIALECT_OVERRIDE_JOIN_FORMULA );
		consumer.accept( DIALECT_OVERRIDE_WHERES );
		consumer.accept( DIALECT_OVERRIDE_WHERE );
		consumer.accept( DIALECT_OVERRIDE_FILTER_OVERRIDES );
		consumer.accept( DIALECT_OVERRIDE_FILTERS );
		consumer.accept( DIALECT_OVERRIDE_FILTER_DEF_OVERRIDES );
		consumer.accept( DIALECT_OVERRIDE_FILTER_DEFS );
		consumer.accept( DIALECT_OVERRIDE_VERSION );
	}
}

